name: Build
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: swift builds

